### ISSUE TITLE
Market should be of Country Type

### ISSUE THREAD

**Issue by operezfuentes** [travelgateX/Issue-tracker#23]
GraphQL is a strongly typed language.

**CriteriaSearch.nationality** is correctly using Country type, but **CriteriaSearch.market** is implemented as String.

For my supplier's knowledge, all markets could/should be expressed as Countries.

**Comment by abasalo** [comment]
I'm sure your are right! It is something that has not been reviewed yet.

Did the type of string in market tag because our providers could have native codes. Here put link about our [Legacy API](http://tech.xmltravelgate.com/docs/hotel/DSF/MarketList)

We had to adapt it based on the standard. We are working to standardize it for all suppliers. We will analyze what you say to make the change. 

We will let you know as soon as possible when we review what is the best way to not alter our clients.

Thanks for the recommendation!

**Comment by abasalo** [comment]
We changed our schema, from now the nationality will use the same standard as the market tag:

![imagen](https://user-images.githubusercontent.com/6781001/52476959-adabf400-2ba0-11e9-8053-4eecf5d2233a.png)

Thank you for the comments!
